<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dx</string>
	</array>
	<key>name</key>
	<string>DATEX</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#compile</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#insert</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#insert_val</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings-single</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings-double</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#slot</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#url</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#key</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#path</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#hex</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#bin</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#oct</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quantity</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#time</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#float</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#int</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#number</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#buffer</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#true</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#false</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#void</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#null</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pointer</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pointer-label</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pointer-transform</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#pointer-create</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#shebang</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-block</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#comment-block2</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#endpoint-person</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#endpoint-anonymous</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#endpoint-institution</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#type</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>bin</key>
		<dict>
			<key>match</key>
			<string>0b[01_]+</string>
			<key>name</key>
			<string>constant.numeric.bin.datex</string>
		</dict>
		<key>buffer</key>
		<dict>
			<key>match</key>
			<string>`([A-Fa-f0-9_]*)`</string>
			<key>name</key>
			<string>buffer.datex</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string># .*?$</string>
			<key>name</key>
			<string>comment.line.datex</string>
		</dict>
		<key>comment-block</key>
		<dict>
			<key>begin</key>
			<string>##*</string>
			<key>end</key>
			<string>##*</string>
			<key>name</key>
			<string>comment.block.datex</string>
		</dict>
		<key>comment-block2</key>
		<dict>
			<key>begin</key>
			<string>/\*</string>
			<key>end</key>
			<string>\*/</string>
			<key>name</key>
			<string>comment.block.datex</string>
		</dict>
		<key>comment2</key>
		<dict>
			<key>match</key>
			<string>\/\/.*?$</string>
			<key>name</key>
			<string>comment.line.datex</string>
		</dict>
		<key>compile</key>
		<dict>
			<key>match</key>
			<string>compile\b</string>
			<key>name</key>
			<string>insert.datex</string>
		</dict>
		<key>endpoint-anonymous</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>(@@[A-Za-z0-9À-ž-_]{1,32})</string>
			<key>end</key>
			<string>\b</string>
			<key>name</key>
			<string>entity.name.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9À-ž-_]{1,32}</string>
					<key>name</key>
					<string>entity.name.endpoint.name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>entity.name.endpoint.wildcard</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:(?!:)</string>
					<key>name</key>
					<string>punctuation</string>
				</dict>
				<dict>
					<key>match</key>
					<string>/</string>
					<key>name</key>
					<string>punctuation</string>
				</dict>
			</array>
		</dict>
		<key>endpoint-institution</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>(@\+[A-Za-z0-9À-ž-_]{1,32})</string>
			<key>end</key>
			<string>\b</string>
			<key>name</key>
			<string>entity.name.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9À-ž-_]{1,32}</string>
					<key>name</key>
					<string>entity.name.endpoint.name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>entity.name.endpoint.wildcard</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:(?!:)</string>
					<key>name</key>
					<string>operator.seperator.datex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>/</string>
					<key>name</key>
					<string>operator.seperator.datex</string>
				</dict>
			</array>
		</dict>
		<key>endpoint-person</key>
		<dict>
			<key>applyEndPatternLast</key>
			<integer>1</integer>
			<key>begin</key>
			<string>(@[A-Za-z0-9À-ž-_]{1,32})</string>
			<key>end</key>
			<string>\b</string>
			<key>name</key>
			<string>entity.name.function</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>[A-Za-z0-9À-ž-_]{1,32}</string>
					<key>name</key>
					<string>entity.name.endpoint.name</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\*</string>
					<key>name</key>
					<string>entity.name.endpoint.wildcard</string>
				</dict>
				<dict>
					<key>match</key>
					<string>:(?!:)</string>
					<key>name</key>
					<string>operator.seperator.datex</string>
				</dict>
				<dict>
					<key>match</key>
					<string>/</string>
					<key>name</key>
					<string>operator.seperator.datex</string>
				</dict>
			</array>
		</dict>
		<key>false</key>
		<dict>
			<key>match</key>
			<string>false</string>
			<key>name</key>
			<string>constant.language.boolean.false.datex</string>
		</dict>
		<key>float</key>
		<dict>
			<key>match</key>
			<string>(((\d_?)+\.)?(\d_?)+((E|e)(-|\+)?(\d_?)+)|(\d_?)+\.(\d_?)+)(?! *\:)</string>
			<key>name</key>
			<string>constant.numeric.decimal.datex</string>
		</dict>
		<key>hex</key>
		<dict>
			<key>match</key>
			<string>0x[0-9a-fA-F]+</string>
			<key>name</key>
			<string>constant.numeric.hex.datex</string>
		</dict>
		<key>insert</key>
		<dict>
			<key>match</key>
			<string>insert\b</string>
			<key>name</key>
			<string>insert.datex</string>
		</dict>
		<key>insert_val</key>
		<dict>
			<key>match</key>
			<string>\?\d*</string>
			<key>name</key>
			<string>insert.datex</string>
		</dict>
		<key>int</key>
		<dict>
			<key>match</key>
			<string>\b(\d_?)+\b(?! *\:)</string>
			<key>name</key>
			<string>constant.numeric.integer.datex</string>
		</dict>
		<key>key</key>
		<dict>
			<key>match</key>
			<string>[A-Za-z0-9À-ž_-]+?\s*(?=\:)(?!\:\:)</string>
			<key>name</key>
			<string>key.datex</string>
		</dict>
		<key>keywords</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\b(typeof|response|clone_collapse|collapse|defer|plugin|named|default|scope|run|export|as|from|var|val|ref|const|new|to|iterator|skip|leave|maybe|accept|try|yeet|next|keys|has|iterate|assert|matches|freeze|seal|function|do|await|get|base|transaction|debugger|extends|implements|constructor|destructor|creator|replicator|template|return|exit|use|delete|count|about|if|else|while|origin|copy|clone|type|subscribers|always)\b</string>
					<key>name</key>
					<string>keyword.control.datex</string>
				</dict>
			</array>
		</dict>
		<key>null</key>
		<dict>
			<key>match</key>
			<string>null</string>
			<key>name</key>
			<string>constant.language.boolean.null.datex</string>
		</dict>
		<key>number</key>
		<dict>
			<key>match</key>
			<string>nan|infinity</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<key>oct</key>
		<dict>
			<key>match</key>
			<string>0o[0-7_]+</string>
			<key>name</key>
			<string>constant.numeric.oct.datex</string>
		</dict>
		<key>path</key>
		<dict>
			<key>match</key>
			<string>\.\.?\/(?:[-a-zA-Z0-9(@:%_\+.~#?&amp;//=]|\\.)+</string>
			<key>name</key>
			<string>url.datex</string>
		</dict>
		<key>pointer</key>
		<dict>
			<key>match</key>
			<string>\$((?:[A-Fa-f0-9]{2}|[xX]([A-Fa-f0-9])){1,26})</string>
			<key>name</key>
			<string>variable.pointer.datex</string>
		</dict>
		<key>pointer-create</key>
		<dict>
			<key>match</key>
			<string>\$\$</string>
			<key>name</key>
			<string>variable.pointer.datex</string>
		</dict>
		<key>pointer-label</key>
		<dict>
			<key>match</key>
			<string>\$([A-Za-z0-9À-ž_]{1,25})</string>
			<key>name</key>
			<string>variable.pointer.datex</string>
		</dict>
		<key>pointer-transform</key>
		<dict>
			<key>match</key>
			<string>\$(?=\()</string>
			<key>name</key>
			<string>variable.pointer.datex</string>
		</dict>
		<key>quantity</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>quantity.datex</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>unit.datex</string>
				</dict>
			</dict>
			<key>match</key>
			<string>((?:(?:(?:\d_?)+\.)?(?:\d_?)+(?:(?:E|e)(?:-|\+)?(?:\d_?)+)|(?:\d_?)+\.(?:\d_?)+)|(?:(?:\d_?)+))(?! *\:)((?:[YZEPTGMkhdcmµunpfazy]?[A-Za-z€¢$¥Ω£₽⁄⁄]{1,4}(?:\^-?\d{1,4})?)(?:[*\/][YZEPTGMkhdcmµunpfazy]?[A-Za-z€¢$%¥Ω£₽]{1,4}(?:\^-?\d{1,4})?)*)</string>
			<key>name</key>
			<string>constant.numeric.quantity.datex</string>
		</dict>
		<key>shebang</key>
		<dict>
			<key>match</key>
			<string>^#!.*</string>
			<key>name</key>
			<string>comment.line.datex</string>
		</dict>
		<key>slot</key>
		<dict>
			<key>match</key>
			<string>#[A-Za-z0-9À-ž_]+</string>
			<key>name</key>
			<string>slot.datex</string>
		</dict>
		<key>strings-double</key>
		<dict>
			<key>begin</key>
			<string>&quot;</string>
			<key>end</key>
			<string>&quot;</string>
			<key>name</key>
			<string>string.quoted.double.datex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.datex</string>
				</dict>
			</array>
		</dict>
		<key>strings-single</key>
		<dict>
			<key>begin</key>
			<string>&#39;</string>
			<key>end</key>
			<string>&#39;</string>
			<key>name</key>
			<string>string.quoted.single.datex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.datex</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>source.datex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#compile</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#insert</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#insert_val</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings-double</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#slot</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#key</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#url</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#path</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#hex</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bin</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#oct</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quantity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#time</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#float</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#int</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#buffer</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#true</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#false</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#void</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#null</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pointer</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pointer-label</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pointer-transform</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pointer-create</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#endpoint-person</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>time</key>
		<dict>
			<key>match</key>
			<string>~((\d{1,5}-\d{1,2}-\d{1,2})|(\d{1,5}-\d{1,2}-\d{1,2}(T| )\d{1,2}:\d{1,2}(:\d{1,2}(.\d{1,3})?)?Z?)|(\d{1,2}:\d{1,2}(:\d{1,2}(.\d{1,3})?)?))~</string>
			<key>name</key>
			<string>constant.numeric.time.datex</string>
		</dict>
		<key>true</key>
		<dict>
			<key>match</key>
			<string>true</string>
			<key>name</key>
			<string>constant.language.boolean.true.datex</string>
		</dict>
		<key>type</key>
		<dict>
			<key>begin</key>
			<string>&lt;(?:(\w+?):)?([A-Za-z0-9À-ž_+-]+)(/[A-Za-z0-9À-ž_+-]*)*</string>
			<key>end</key>
			<string>&gt;</string>
			<key>name</key>
			<string>type.datex</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\(</string>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>source.datex</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>#compile</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#insert</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#insert_val</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings-single</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#strings-double</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#slot</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#key</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#url</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#path</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#hex</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#bin</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#oct</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#keywords</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#quantity</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#time</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#float</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#int</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#number</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#buffer</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#true</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#false</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#void</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#null</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pointer</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pointer-label</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pointer-transform</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#pointer-create</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#comment-block</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#endpoint-person</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#endpoint-anonymous</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#endpoint-institution</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#type</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>url</key>
		<dict>
			<key>match</key>
			<string>[a-zA-Z0-9_]+:\/\/((?:[-a-zA-Z0-9(@:%_\+.~#?&amp;//=]|\\.)+)</string>
			<key>name</key>
			<string>url.datex</string>
		</dict>
		<key>void</key>
		<dict>
			<key>match</key>
			<string>void</string>
			<key>name</key>
			<string>constant.language.boolean.void.datex</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.datex</string>
	<key>uuid</key>
	<string>1e813a63-84c0-4ddb-aa5c-6b49cec5dbda</string>
</dict>
</plist>
