pub mod atom;
use crate::compiler::lexer::Token;
pub type TokenInput<'a> = &'a [Token];
pub mod array;
pub mod binary_operation;
pub mod chain;
pub mod decimal;
pub mod endpoint;
pub mod function;
pub mod integer;
pub mod key;
pub mod literal;
pub mod object;
pub mod text;
pub mod tuple;
pub mod unary;
pub mod utils;
