vars: {
  d2-config: {
    theme-overrides: {
      B1: "#69B9D5"
      B2: "#D44778"
      B3: "#5D5D5D"
      B4: "#404040"
      B5: "#252525"
      B6: "#313244"

      AA2: "#C64472"
      AA4: "#252525"
      AA5: "#313244"

      AB4: "#252525"
      AB5: "#313244"
    }
  }
}
